### ISSUE TITLE
Source code availability of the MPIR library

### ISSUE THREAD

**Issue by dimitar10** [pung-project/mpir#1]
Hello,

Are there any plans for publishing the source code of the MPIR library?

Best regards,
Dimitar

**Comment by sga001** [comment]
Take a look at: https://github.com/sga001/mxpir.

It has the MPIR code that works with XPIR. If you need MPIR code that works with SealPIR, I can give that to you as well. The only issue is that the code I have is not compatible with the current version of SealPIR (since the API has changed).

**Comment by dimitar10** [comment]
Thank you very much for the quick response! Actually I would like to look into the MPIR code that works with SealPIR (it is alright if it's not compatible with the current version). I'm assuming it works with the then-current version of SealPIR, when the MPIR code was written.

**Comment by sga001** [comment]
Sure.

https://github.com/sga001/mpir

Give it a shot and let me know if you have issues. It does not work with the latest version of SealPIR.

**Comment by dimitar10** [comment]
Thank you very much! 

The sources compile without a problem. Some of the tests appear not to run to completion (the `cargo test` command is ended with `SIGKILL`), but at the moment I can't tell exactly why. I will update the issue as soon as I have some notion of what goes wrong during the execution of the tests.

**Comment by sga001** [comment]
hmm, I'd have to check. If you are getting a SIGKILL it is likely from the SealPIR C++ code or the sealpir-rust bindings (in the sealpir-bindings directory).

See if the tests in SealPIR-rust (without mpir) run without issue.

Another possible issue could be concurrency. I remember one of the earlier versions of SealPIR had some issues with concurrent operations. Rust by default runs multiple tests concurrently (there is a flag you can pass to cargo test to run 1 test at a time: ``cargo test -- --test-threads=1``).

Let me know if either of these things reveals the root cause.

**Comment by dimitar10** [comment]
`SealPIR-rust` tests and benches complete flawlessly and I can replicate the computational costs from Figure 9 of the 2018 paper. The values that I'm getting are close to those in the paper: the first row values for `QUERY` are in the ballpark of 3.5 milliseconds vs. the 3.37 millisecond in the paper, but also other values such as server's `EXPAND` for n= 2^18 entries was 100.88 milliseconds ~ 0.1 seconds vs 0.11 seconds in the paper; etc.). 

The tests were run within a Ubuntu 18.04 Docker container, running on a 6 cores/12 threads Xeon E-2176M with 32 GiB of memory (previous attempts were on a 18.04 virtual machine with 4 cores and 16 GiB / 24 GiB of memory).

The state with the `mpir` tests and benches is as follows:
```
test pbc::test::test_choices ... ok
test pbc::test::test_cuckoo ... ok
test pbc::test::test_pung ... ok
test pbc::test::test_replication ... ok
test pbc::test::test_sharding ... ok

test mpir_sizes: 
 - batch_size 16 = OK
 - batch_size_64 = OK
 - batch_size_256 = NOK (reaches almost 32 GiBs of memory and gets killed by the system with SIGKILL)

test multipir_test_pung: 
- batch_size_16 = OK
- batch_size_64 = OK
- batch_size_256 = OK (although frequent assertion failures at line 466 of tests/multipir.rs)

multipir_test_replication = OK
multipir_test_sharding = OK
multipir_test_choice = OK
multipir_test_cuckoo = OK
```

The `mpir` benchmarks appear to be OK for batch size k=16 and finish without any errors (for other batch sizes the benchmarks are still running, and I'll post an update as soon as they finish). However, I noticed a mismatch with the results for Figure 12 in the paper. For instance, I ran the benchmark for `query_cuckoo` for all batch sizes, and the results are:


query_cuckoo_d2_n1048576/16                                                                          
                        time:   [94.697 ms **95.342 ms** 96.000 ms]
query_cuckoo_d2_n1048576/64                                                                          
                        time:   [347.45 ms **350.00 ms** 352.19 ms]
query_cuckoo_d2_n1048576/256                                                                          
                        time:   [1.3822 s **1.3964 s** 1.4079 s]

and if I divide the mean times by their respective batch sizes, it would result in something comparable to the results in the paper i.e. multi-query times for cuckoo of 5.95 ms, 5.468 ms and 5.45 ms for k = 16, 64 and 256 respectively. I'd like to ask if I'm making some sort of a fundamental mistake here, because I can't otherwise explain the results produced by the benchmark.

**Comment by sga001** [comment]
Hi, good to hear that it is working.

Thanks for replicating the results! As for the mpir, yes the results in Figure 12 represent the **amortized** per-request cost, as stated in the caption (i.e., how much it costs to fetch 1 object). The cost given by the benchmark is the total cost for fetching k objects. So yes, divide by k and that should give you the amortized per-request cost.

Let me know if you have any other questions.

**Comment by sga001** [comment]
I will look into the batch_size 256 case for mpir where it is getting killed. I'll also check the line 466 in tests/multipir.rs

Thanks again for reporting this.

**Comment by dimitar10** [comment]
Thank you very much for the quick reply!

After running all of the benchmarks, only few failed to complete, namely:

`reply_pung_d2_n1048576/256` and `decode_pung_d2_n1048576/256`, both with the same error: 

```
error: process didn't exit successfully: ... (signal: 9, SIGKILL: kill)
```

I've yet to run the Figure 12 mpir benchmarks for `n < 2^20`, perhaps there won't be any failed benchmarks if I reduce the database size. I will report this as well, as soon as I run the benchmarks.

**Comment by dimitar10** [comment]
Hello Sebastian,

After re-reading your dissertation (as well as the OSDI '16 and S&P '18 papers) I would like to ask the following:

- if we have a hypothetical system that uses a database where the number of elements is fixed to an arbitrary `2^n` and there are no insertions or deletions whatsoever (the database is an archive sort of speak), is it sufficient for the `setup` portion of the mpir protocol to be run only once for a given `k` , and then be skipped for any subsequent queries for the same `k`? As far as I understand, if `k` changes its value then it has to be run again.

- in addition to the above, if we also fix `k`, so that it never changes its values (for example `k=256`), will it be sufficient to only run the `setup` stage once, to retrieve any set of `k` labels, or it has to be run for each different set of `k` labels?

Also I would like to ask if you think that it's more appropriate to shift this discussion to the mpir github repo instead of here.

**Comment by sga001** [comment]
I think for the scenario you describe you can run setup once. One issue I can imagine is that you might get really unlucky in the following sense: the allocation of elements to buckets (which is random-ish) ends up being the worst-case scenario for what your clients want. This will limit your performance.

What I mean is: suppose your application is such that they almost always want elements 3, 5, 8, and 19. Suppose after you ran setup, this exact combination is just not possible (this happens with small but non-negligible probability). Then you will never be able to retrieve all 4 elements in a single multiquery (and recall that you cannot do data-dependent follow up multiqueries since that would leak information).

On the other hand if you re-encode the database every once in a while, you can bound the impact of a bad-luck setup.

**Comment by dimitar10** [comment]
Hello Sebastian,

I have a question about calculating and finding the correct value of `t'`. Namely, in section 8.3 of the dissertation, `t'` is calculated to have the following values:

```
for the original 2^20-entry database, t' = 2^10 (resulting in F=12), 
whereas for the average bucket of 2^13 entries, t'=2^15 (resulting in F=8).
```

However, upon using the SealPIR functions that do the calculation and double-checking the equations from the paper with a numerical solver, the result appears to be `t' = 2^11` for that particular set of parameters, which consequently will change `F`, and in turn the values for the network costs. For other values of the parameters, e.g. `n=2^13` the calculation seems to be correct (`t'` is indeed `2^15`).

Is there a particular reason for the discrepancy between the calculations?

**Comment by sga001** [comment]
Hello,

It's quite possible that I made a rounding mistake during the computation of t' for that experiment. As you note, we have the right number for the 2^13 entry case, but it might be slightly off for the 2^20 case (I haven't recomputed it myself, but I'll trust your solver). The good news is that if the correct t' is larger (as you point out), our results should actually be better than what we report!

Having said that, the newest version of SealPIR no longer performs this optimization and instead performs the inverse scalar multiplication since it isn't that expensive anyway, and allows us to further reduce network communication by packing more data into each FV plaintext.
